name: BedWars
version: 1.0.1-BETA
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]
main: Bluplayz\BedWars
author: KitrosMC, SlennyNation, ZPlayzMCPE
commands:
    Bedwars:
        description: Bedwars Main Command
        aliases: [bw]
    Start:
        description: Bedwars Forcestart Command
