name: BedWars
version: 1.0.1-BETA
api: [3.0.0-ALPHA9, 3.0.1]
main: Bluplayz\BedWars
author: ZPlayzMCPE, SlennyNation
commands:
    Bedwars:
        description: Bedwars Main Command
        aliases: [bw]
    Start:
        description: Bedwars Forcestart Command
